config/routes.rb
Rails.application.routes.draw do
  

  

  resources :businesses do
    resources :events
  	resources :reviews
  end

  devise_for :users
  resources :user_profiles
  root to: 'static_pages#home'

  get 'contact' => 'static_pages#contact'

  get 'about' => 'static_pages/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord
	belongs_to :user
	has_many :events
	has_many :vaccancies
	has_many :reviews
	def self.search(search)
  		where("business_name LIKE ?", "%#{search}%") 
	end
	mount_uploader :business_photo, BusinessPhotoUploader
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :user
	belongs_to :business
	mount_uploader :event_photo, EventPhotoUploader
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
	belongs_to :business
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :user_profile
  has_many :businesses
  has_many :events
  has_many :reviews
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
	belongs_to :user
	has_many :businesses
	has_many :vaccancies
	mount_uploader :avatar, AvatarUploader
end

app/models/vaccancy.rb
class Vaccancy < ApplicationRecord
   belongs_to :user
   belongs_to :business

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
before_action :authenticate_user!, only: [:new,:show, :edit]
before_action :find_businesses, only: [:show, :edit, :update, :destroy]
	def index
		@businesses = Business.all
		if params[:search]
    		@businesses = Business.search(params[:search]).order("created_at DESC")
  		else
    		@businesses = Business.all.order('created_at DESC')
  		end
	end
	def new
	 @business = current_user.businesses.build 
	end

	def create
		@business = current_user.businesses.build (business_params)

		if @business.save

			 flash[:notice] = "you have submitted #{@business.business_name}"
			redirect_to @business
		else

			render :new
		end
	end

	def edit
	end

	def update
		if @business.update_attributes(business_params)

			flash[:notice] = "successfully updated"
			redirect_to @business
		else
			render :edit
		end
	end

	def show
	end

	# def delete
	# end

	# def destroy
	# 	@user_profile.destroy
	# 	redirect_to root_path
	# end


private

	def find_businesses
		@business = Business.find(params[:id])
	end

    def business_params
     params.require(:business).permit(:business_name, :business_photo, :business_email, :business_description, :business_catagory, :mobile_number, :business_address)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :authenticate_user!
 	before_action :find_business
	before_action :find_event, only: [:show, :edit, :update, :destroy]
	
	def index
		@events = Event.all
	end
	def new
		@event = Event.new
	end

	def create
		@event = Event.new(event_params)
		@business.events << @event
		current_user.events << @event

		if @event.save
			flash[:notice] = "welcome!!!!"
			redirect_to business_event_path(@business, @event)
		else
			render :new
		end
	end

	def edit
	end

	def update	
		if @event.update(event_params)
			flash[:notice] = "updated!!!!"
			redirect_to business_event_path(@business, @event)
		else
			render :edit
		end
	end

	def destroy
		@event.destroy
		redirect_to @event
	end

	private 

	def event_params
		params.require(:event).permit(:event_name, :event_description, :starting_date, :end_date, :event_photo)
	end

	def find_event
		@event = Event.find(params[:id])
	end 

	def find_business
		@business = Business.find(params[:business_id])
	end

	
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :find_business
	before_action :find_review, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.business_id = @business.id
		@review.user_id = current_user.id

		if @review.save
			redirect_to business_path(@business)
		else
			render 'new'
		end
	end

	def edit
	end

	def update	
		if @review.update(review_params)
			redirect_to business_path(@business)
		else
			render 'edit'
		end
	end
	def show
	end
	def destroy
		@review.destroy
		redirect_to business_path(@business)
	end

	private 

		def review_params
			params.require(:review).permit(:ratting, :comment)
		end

		def find_business
			@business = Business.find(params[:business_id])
		end

		def find_review
			@review = Review.find(params[:id])
		end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@businesses = Business.all
		if params[:search]
    		@businesses = Business.search(params[:search]).order("created_at DESC")
  		else
    		@businesses = Business.all.order('created_at DESC')
  		end
  end

  def contact
  end

  def about
  end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
before_action :authenticate_user!, only: [:new,:show, :edit]
before_action :find_user_profiles, only: [:show, :edit, :update, :destroy]

	def new
	 @user_profile = current_user.build_user_profile 
	end

	def create
		@user_profile = current_user.build_user_profile(user_params)

		if @user_profile.save

			 flash[:notice] = "welcome #{@user_profile.username}"
			redirect_to @user_profile
		else

			render :new
		end
	end

	def edit
	end

	def update
		if @user_profile.update_attributes(user_params)

			flash[:notice] = "profile successfully updated"
			redirect_to @user_profile
		else
			render :edit
		end
	end

	def show
	end

	# def delete
	# end

	# def destroy
	# 	@user_profile.destroy
	# 	redirect_to root_path
	# end


private

	def find_user_profiles
		@user_profile = UserProfile.find(params[:id])
	end

    def user_params
     params.require(:user_profile).permit(:username, :bio, :avatar, :sex, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/businesses_helper.rb
module BusinessesHelper
	
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/businesses/_form.html.erb
<div class="input-field">
	<%= f.label :business_photo, "Business Photo" %> <br><br>
	<%= f.file_field :business_photo %>
</div>
<div class="input-field">
	<%= f.text_field :business_name, autofocus: true, placeholder: "Business Name" %>
</div>
<div class="input-field">
	<%= f.email_field :business_email, autofocus: true, placeholder: "Business Email" %>
</div>
<div class="input-field">
	<%= f.label :business_catagory, "Business Catagory" %> <br>
	<%= f.select :business_catagory, options_for_select([ "Restaurants", "Cafe", "Hotels and travel", "health and medical","arts and entertment", "professional Services" ])%>
</div>
<div class="input-field">
	<%= f.text_area :business_description, autofocus: true, placeholder: "Business Description" %>
</div>

<div class="input-field">
	<%= f.text_field :mobile_number, autofocus: true, placeholder: "Business Phone Number" %>
</div>
<div class="input-field">
	<%= f.text_field :business_address, autofocus: true, placeholder: "Business Address" %>
</div>

app/views/businesses/_reviewshow.html.erb
<% @business.reviews.each do |f|%>

	<div class="col s12 m7 l6">
		<div class="card horizontal">
			<div class="card-image">
				<%= image_tag(f.user.user_profile.avatar_url, class: "responsive-img") %>
			</div>
			<div class="card-stacked">
				<div class="card-content">
					<span><%= f.user.user_profile.username%></span>
					<div class="review-rating" data-score="<%= f.ratting %>"></div>
					<p><%= f.comment%></p>
				</div>
				<div class="card-action">
					<%= link_to "Edit", edit_business_review_path(f)%>
				<%= link_to "Delete", business_review_path(f), method: :delete, data: { confirm: "Are you sure?" } %>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/businesses/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col s12 l8 m8 offset-l2">
			<div class="card">
				<div class="card-content black-text">
					<span class="card-title">Edit Business info</span>
					<%= form_for(@business) do |f|%>
						<%= render(:partial => "form", :locals => {:f => f}) %>
	            		<div class="acton">
	              			<%= f.button "Update", class: "btn center"%>
	            		</div>
	            	<%end%>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/businesses/index.html.erb
<%= form_tag(businesses_path, :method => "get", id: "search-form") do %>
    <div class="row">
        <div class="col l8 s8 m8" style="padding-left:200px;"><%= text_field_tag :search, params[:search], placeholder: "Search By Business name" %></div>
    <div class="col l4 s4 m4" style="padding-top:10px;"><%= submit_tag "Search", class: "btn #1b5e20 green darken-4"%></div>
    </div>
<% end %>

<h1>businesses</h1>
<% @businesses.each do |f|%>

    <div class="col s12 m6 l6">
    <div class="card horizontal">
      <div class="card-image">
        <%= image_tag f.business_photo_url, class: "responsive-img"%>
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <span class="card-title"><%=f.business_name%></span>
          <p><%= f.business_description%></p>
        </div>
        <div class="card-action">
           <%= link_to("write a review", new_business_review_path(f) , class: "btn #212121 grey darken-4") %>
           <%= link_to("details", business_path(f) , class: "btn #212121 grey darken-4") %>
        </div>
      </div>
    </div>
  </div>
<%end%>

app/views/businesses/new.html.erb
<div class="container">
	<div class="row">
		<div class="col s12 l8 m8 offset-l2">
			<div class="card">
				<div class="card-content black-text">
					<span class="card-title">Registring Business info</span>
					<%= form_for(@business) do |f|%>
						<%= render(:partial => "form", :locals => {:f => f}) %>
	            		<div class="acton">
	              			<%= f.button "Submit", class: "btn center"%>
	            		</div>
	            	<%end%>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/businesses/show.html.erb
<div class="">
	<div class="row">
		<div class="col s12 m12 l6">
			<div class="row">
				<div class="col s12 m12 l12">
					<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d126115.11523351159!2d38.7781448!3d8.96317685!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2set!4v1498391871412" width="634" height="430" frameborder="0" style="border:0" allowfullscreen></iframe>
				</div>
				<div class="col s12 m12 l6">
					<div class="card z-depth-0">
						<div class="card-content black-text">
							<ul>
								<li><i class="material-icons">email</i><%= @business.business_email%></li>
								<li><i class="material-icons">phone</i><%= @business.mobile_number%></li>
								<li><i class="material-icons">label</i><%= @business.business_catagory%></li>
								<li><i class="material-icons">location_on</i><%= @business.business_address%></li>
								<li><%=link_to "contact owner", "#", class: "btn black"%></li>
							</ul>
						</div>
					</div>
				
				</div>
			</div>
			
			
		</div>
		<div class="col.s12.m12.l6">
			<span><%= @business.business_name%></span><span style="visibility: hidden;">x</span>
			<%= link_to("Add Event", new_business_event_path(@business) , class: "btn #212121 grey darken-4") %> 
			
				<%= link_to("Edit Business", edit_business_path , class: "btn #212121 grey darken-4") %>
			
				<%= link_to("Write A Review", new_business_review_path(@business) , class: "btn #212121 grey darken-4") %>
			
			 <br><br>
			<%= image_tag @business.business_photo_url, size:"250x250", class: "responsive-img"%>
			<p><%= @business.business_description%></p>
				
			
		</div>
	</div>
</div>

<div class="row">
	<div class="col s12 m12 16">
		<div class="reviews">
			<h1> Reviews </h1>
			<%= render 'reviewshow' %>

		</div>
	</div>
</div>









<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>

<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>

app/views/events/_form.html.erb
<div class="input-field">
	<%= f.label :event_photo, "Event Photo" %> <br><br>
	<%= f.file_field :event_photo %>
</div>
<div class="input-field">
	<%= f.text_field :event_name, autofocus: true, placeholder: "Event Name" %>
</div>
<div class="input-field">
	<%= f.text_area :event_description, autofocus: true, placeholder: "Event Description" %>
</div>

<div class="input-field">
	<%= f.text_field :starting_date, autofocus: true, placeholder: "Starting Date" %>
</div>
<div class="input-field">
	<%= f.text_field :end_date, autofocus: true, placeholder: "Ending Date" %>
</div>

app/views/events/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col s12 l8 m8 offset-l2">
			<div class="card">
				<div class="card-content black-text">
					<span class="card-title">Edit Event info</span>
					<%= form_for [@business, @event] do |f|%>
						<%= render(:partial => "form", :locals => {:f => f}) %>
	            		<div class="acton">
	              			<%= f.button "Update", class: "btn center"%>
	            		</div>
	            	<%end%>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/events/index.html.erb
<div class="row">
<h1>Events</h1>
<% @events.each do |f|%>
  
      <div class="col s12 m6 l6">
      <div class="card horizontal">
        <div class="card-image">
          <%= image_tag f.event_photo_url, class: "responsive-img"%>
        </div>
        <div class="card-stacked">
          <div class="card-content">
            <span class="card-title"><%=f.event_name%></span>
            <p><%= f.event_description%></p>
          </div>
          <div class="card-action">
             <%= link_to("details", business_event_path(f.business,f.id) , class: "btn #212121 grey darken-4") %>
          </div>
        </div>
      </div>
    </div>
  
<%end%>
</div>

app/views/events/new.html.erb
<div class="container">
	<div class="row">
		<div class="col s12 l8 m8 offset-l2">
			<div class="card">
				<div class="card-content black-text">
					<span class="card-title">Add Event</span>
					<%= form_for [@business, @event] do |f|%>
						<%= render(:partial => "form", :locals => {:f => f}) %>
	            		<div class="acton">
	              			<%= f.button "Submit", class: "btn center"%>
	            		</div>
	            	<%end%>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/events/show.html.erb
<div class="container">
	<div class="row">
		<div class="col s12 m12 l4">
			<div class="row">
				<div class="col s12 m12 l12">
					<%= image_tag @event.event_photo_url, class: "responsive-img", size: "450x350"%>
				</div>
				<div class="col s12 m12 l12">
					<div class="card">
						<div class="card-content">
							<span><%= @event.event_name%></span><br>
							<span><%= @event.starting_date%></span><br>
							<span><%= @event.end_date%></span>
							<%= link_to("edit event", edit_business_event_path(@business, @event) ,class: "btn black" ) %>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col s12 m12 l8">
			
			<div class="card">
				<div class="card-content">
					<%= @event.event_description%>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_fab.html.erb
<div class="fixed-action-btn" style="bottom: 3.3em; right: 0.2em;">
	<%= link_to new_business_path, class: "btn-floating btn-large halfway-fab waves-effect waves-light teal" do %>
    	<i class="material-icons">mode_edit</i>
	<% end %>
</div>

app/views/layouts/_footer.html.erb
 <footer class="page-footer">
   <div class="container">
     <div class="row">
       <div class="col l6 s12">
         <h5 class="white-text">Footer Content</h5>
         <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
       </div>
       <div class="col l4 offset-l2 s12">
         <h5 class="white-text">Links</h5>
         <ul>

           <li><% if user_signed_in?%><%= link_to "user profiles new", new_user_profile_path, class: "grey-text text-lighten-3"%><%end%></li>
           <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
           <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
           <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
         </ul>
       </div>
     </div>
   </div>
   <div class="footer-copyright">
     <div class="container">
       © 2017 Copyright Text
       <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
     </div>
   </div>
 </footer>

app/views/layouts/_main_nav.html.erb
<nav>
  <div class="nav-wrapper">
  	<a href="#" data-activates="mobile-demo" class="button-collapse show-on-large" data-turbolinks="false"><i class="material-icons">menu</i></a>
    
    
    <ul id="nav-mobile" class="left hide-on-med-and-down">
      <li><%= link_to "Write a Review", "#"%></li>
      <li><%= link_to "Events", business_event_path(Business.all.ids, Event.all.ids) %></li>
      
    </ul>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%= link_to("Home", root_path)%></li>
      <% if user_signed_in?%>
        <li><%= link_to("Logout", destroy_user_session_path, method: :delete )%></li>
      <% else%>
        <li><%= link_to("Sign Up", new_user_registration_path)%></li>
        <li><%= link_to("Login", new_user_session_path)%></li>
      <%end%>

      
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <li><%= link_to "Write a Review", ""%></li>
      <li><%= link_to "Events", "#"  %></li>
      
      <li><%= link_to "Write a Review", "#"%></li>
      <li><%= link_to("Sign Up", new_user_registration_path)%></li>
      <li><%= link_to("Login", new_user_session_path)%></li>
    </ul>
  </div>
      
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dejaf <%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="#e8f5e9 green lighten-5">
    <header>
      <% if !current_page?(new_user_registration_path) &&  !current_page?(new_user_session_path) &&  !current_page?(new_user_profile_path)%>
          <%= render '/layouts/main_nav'%>
      <% end %>
    </header>
    <main>
        <section class="message">
            <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        </section>
        <section class="main-section">
            <%= yield %>
        </section>
      <% if !current_page?(new_user_registration_path) &&  !current_page?(new_user_session_path) &&  !current_page?(new_user_profile_path) && user_signed_in?%>
        <%= render '/layouts/fab'%>
      <% end %>
      
      
    </main>
    <% if !current_page?(new_user_registration_path) &&  !current_page?(new_user_session_path) &&  !current_page?(new_user_profile_path )%>
      <footer>
        <%= render '/layouts/footer'%>
      </footer>
    <% end %>

  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for([@business, @business.reviews.build]) do |f| %>
	<div id="rating-form">
		<label> Rating </label>
	</div>
	<%= f.text_area :comment %>
	<%= f.button :submit, :class => "btn" %>
<% end %>


<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[ratting]'
	});
</script>

app/views/reviews/_review.html.erb
<div class="review">
	<div class="review-rating" data-score="<%= review.ratting %>"></div>
	<p class="review-comment"><%= review.comment %></p>

	<% if user_signed_in? %>
		<% if review.user_id == current_user.id %>
			<div class="links btn-group">
				<%= link_to "Edit", edit_business_review_path(review.business, review), class: "btn btn-custom" %>
				<%= link_to "Delete", business_review_path(review.business, review), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
			</div>
		<% end %>
	<% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col s12 m12 l12">
	<div class="edit-review-form">
		<h1> Edit Review </h1>
			<%= form_for([@business, @review]) do |f| %>
				<div id="rating-form">
					<label> Rating </label>
				</div>
				<%= f.text_area :comment %>
				<%= f.button :submit, :class => "btn" %>
			<% end %>
	</div>
</div>


<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[ratting]'
	});
</script>

app/views/reviews/new.html.erb
<div class="col s12 l12 m12">
	<div class="new-review-form">
		<h1> Post Review </h1>
		<%= render 'form' %>	
	</div>
</div>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
  <div class="carousel carousel-slider center" data-indicators="true">
    <div class="carousel-fixed-item center">
     
    </div>
    <div class="carousel-item red white-text" href="#one!">
     

    </div>
    <div class="carousel-item amber white-text" href="#two!">
     
    </div>
    <div class="carousel-item green white-text" href="#three!">
     
    </div>
    <div class="carousel-item blue white-text" href="#four!">
      
    </div>
  </div>
<%= form_tag(businesses_path, :method => "get", id: "search-form") do %>
    <div class="row">
        <div class="col l8 s8 m8" style="padding-left:200px;"><%= text_field_tag :search, params[:search], placeholder: "Search By Business name" %></div>
    <div class="col l4 s4 m4" style="padding-top:10px;"><%= submit_tag "Search", class: "btn #1b5e20 green darken-4"%></div>
    </div>
<% end %>
<div class= "row">
<h1>businesses</h1>
<% Business.all.each do |f|%>

    <div class="col s12 m6 l6">
    <div class="card horizontal">
      <div class="card-image">
        <%= image_tag f.business_photo_url, class: "responsive-img"%>
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <span class="card-title"><%=f.business_name%></span>
          <p><%= f.business_description%></p>
        </div>
        <div class="card-action">
           <%= link_to("write a review", new_business_review_path(f) , class: "btn #212121 grey darken-4") %>
           <%= link_to("details", business_path(f) , class: "btn #212121 grey darken-4") %>
        </div>
      </div>
    </div>
  </div>
<%end%>
<br><br><br>
<h1>Events</h1>
<% Business.all.each do |f|%>
  <% f.events.all.each do |e|%>
      <div class="col s12 m6 l6">
      <div class="card horizontal">
        <div class="card-image">
         
        </div>
        <div class="card-stacked">
          <div class="card-content">
            <span class="card-title"><%=e.event_name%></span>
            <p><%= e.event_description%></p>
          </div>
          <div class="card-action">
             <%= link_to("details", business_event_path(f,e) , class: "btn #212121 grey darken-4") %>
          </div>
        </div>
      </div>
    </div>
  <%end%>
<%end%>
</div>

app/views/user_profiles/_form.html.erb
<div class="row">
	<div class="col l4">
		<div class="file-uplaod">
			<%= image_tag("avatar", class: "responsive-img", size: "200x300") %>
			<%= f.file_field :avatar%>
		</div>
		
	</div>
	<div class="col l8">
		<div class="input-field">
			<%=	f.text_field :username ,placeholder: "Username",class: "validate"%>
		</div>
		<div class="row">
			<div class="col l3 s6 m3">
				<div class="input-field">
					<%=	f.text_field :age ,placeholder: "Age",class: "validate"%>
				</div>
			</div>
			<div class="input-field col l4 s6 m3">
				<select name="user_profile[sex]" id="user_profile_sex">
					<option value="male">Male</option>
					<option value="female">Female</option>
				</select>
				
			</div>
			<div class="col l4"></div>
		</div>
		<div class="input-field">
			<i class="material-icons prefix">mode_edit</i>
			<%= f.text_area :bio, class: "materialize-textarea", length:"140" %>
			<%= f.label :bio, "bio"%>
		</div>

	</div>
</div>

app/views/user_profiles/edit.html.erb
<% provide(:title, "| Setting Up Profile") %>
<div class="contanier">
	<div class="row">
		<div class="col l8 offset-l2">

			<div class="card">
				<div class="card-content">
					<span class="center"><%= link_to image_tag("3", :alt => "logo"), root_path %></span>
					<span class="card-title">update User Profile</span>
					<%=	form_for(@user_profile)	do	|f|	%>
						<%= render(:partial => "form", :locals => {:f => f}) %>
						<div class="actions center">
              				<span><%= f.button "updtae Profile", :class => "btn waves-effect waves-light btn-large"%></span>
            			</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/user_profiles/new.html.erb
<% provide(:title, "| Setting Up Profile") %>
<div class="contanier">
	<div class="row">
		<div class="col l8 offset-l2">

			<div class="card">
				<div class="card-content">
					<span class="center"><%= link_to image_tag("3", :alt => "logo"), root_path %></span>
					<span class="card-title">Create User Profile</span>
					<%=	form_for(@user_profile)	do	|f|	%>
						<%= render(:partial => "form", :locals => {:f => f}) %>
						<div class="actions center">
              				<span><%= f.button "Create Profile", :class => "btn waves-effect waves-light btn-large"%></span>
            			</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/user_profiles/show.html.erb
<div class="row">
	<div class="col s12 m12 l12">
		<div class="card center">
			<div class="card-content">
				<div class="image">
					<%= image_tag @user_profile.avatar_url, class: "responsive-img circle"%>
				</div>
				<div class="info">
					<span><%= @user_profile.username %></span><br><br>
					<p><%= @user_profile.bio%></p>
					<%= link_to("Edit Profile", edit_user_profile_path , class: "btn") %>
				</div>
			</div>
		</div>
	</div>
</div>